%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/kevintracy/devel/SpacecraftSimulator/process_csv/second_session/4D_range_w_gps.csv
%
% Auto-generated by MATLAB on 12-Apr-2021 16:39:50

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 21);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["FixMode", "SVinFix", "WeekNum", "TimeofWeek001s", "Latitude1E7deg", "Longitude1E7deg", "HeightAboveEllipsoid001m", "HeightAboveSeaLevel001m", "GeometricDilutionofPrecision001", "PositionDilutionofPrecision001", "HorizontalDilutionofPrecision001", "VerticalDilutionofPrecision001", "TimeDilutionofPrecision001", "ECEFX001m", "ECEFY001m", "ECEFZ001m", "ECEFVX001ms", "ECEFVY001ms", "ECEFVZ001ms", "RawRange1","feeD"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double","double"];
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable("/Users/kevintracy/devel/SpacecraftSimulator/process_csv/second_session/4D_range_w_gps.csv", opts);
tbl(1:11,:) = [];
%% Convert to output type
FixMode = tbl.FixMode;
SVinFix = tbl.SVinFix;
WeekNum = tbl.WeekNum;
TimeofWeek001s = tbl.TimeofWeek001s;
Latitude1E7deg = tbl.Latitude1E7deg;
Longitude1E7deg = tbl.Longitude1E7deg;
HeightAboveEllipsoid001m = tbl.HeightAboveEllipsoid001m;
HeightAboveSeaLevel001m = tbl.HeightAboveSeaLevel001m;
GeometricDilutionofPrecision001 = tbl.GeometricDilutionofPrecision001;
PositionDilutionofPrecision001 = tbl.PositionDilutionofPrecision001;
HorizontalDilutionofPrecision001 = tbl.HorizontalDilutionofPrecision001;
VerticalDilutionofPrecision001 = tbl.VerticalDilutionofPrecision001;
TimeDilutionofPrecision001 = tbl.TimeDilutionofPrecision001;
ECEFX001m = tbl.ECEFX001m;
ECEFY001m = tbl.ECEFY001m;
ECEFZ001m = tbl.ECEFZ001m;
ECEFVX001ms = tbl.ECEFVX001ms;
ECEFVY001ms = tbl.ECEFVY001ms;
ECEFVZ001ms = tbl.ECEFVZ001ms;
RawRange1 = tbl.RawRange1;
feeD = tbl.feeD;
%% Clear temporary variables
clear opts tbl

for i = 1:length(ECEFX001m)
    D.og.ecef(:,i) = [ECEFX001m(i);ECEFY001m(i);ECEFZ001m(i)];
end
D.og.range= RawRange1;
D.og.FEE = feeD;
D.og.SV = SVinFix;
D.og.time = TimeofWeek001s;

clearvars -except B D