sc_properties:
  inertia_rows:
    - [0.00194528, 3.606e-5, -1.003e-5]      # kg⋅m² NOTE: updated from Anh
    - [3.606e-5, 0.00187045, -1.701e-5]      # kg⋅m²
    - [-1.003e-5, -1.701e-5, 0.00199689]     # kg⋅m²
  mass:  177.808e-3                          # kg
  area:  0.01                                # m²
  cd:    1.5                                 # ()
  max_dipoles: [8.8e-3,1.373e-2,8.2e-3]      # A⋅m²
  faces:
    - [1.0, 0.0, 0.0]
    - [-1.0, 0.0, 0.0]
    - [0.0, 1.0, 0.0]
    - [0.0, -1.0, 0.0]
    - [0.0, 0.0, 1.0]
    - [0.0, 0.0, -1.0]

gravity:
  spherical_harmonic_gravity_bool: true      # ()
  gravity_order:  6                          # ()
  gravity_degree: 6                          # ()

environment:
  drag_bool:              true               # ()
  srp_bool:               true               # ()
  gravity_gradient_bool:  true               # ()
  sun_3rd_body_bool:      false              # ()
  moon_3rd_body_bool:     false              # ()

initial_orbital_elements:
  sma:  6.9281363e6                          # m
  ecc:  0.00069140                           # ()
  inc:  1.7209103504296768                   # rad      (98.6009ᵒ)
  raan: 2.22778014514761                     # rad      (127.6424ᵒ)
  argp: 1.6058739541014786                   # rad      (92.0098ᵒ)
  M:    4.680781067631073                    # rad      (268.189ᵒ)

initial_attitude_conditions:
  q0: [0,0,0,1.0]                            # ()       (ᴺqᴮ)
  w0: [0.8, 0.9, -0.2]                           # (rad/s)  (ᴺωᴮ, expr. B)

propagator_parameters:
  epoch: "2016-12-01 16:22:19.0 GPS"         # Epoch (SatelliteDynamics.jl)
  dt_orbital:      10.0                      # sec
  dt_attitude:     0.1                      # sec
  dt_controller:   0.05                       # sec
  final_time_days: 0.8                     # days

inertia_properties:
  sample_new:       false
  scale_std:        0.10
  rotate_std_deg:    10.0

sensor_properties:
  gyro:
    rotate_std_deg: 0.0
    noise_std_degps: 0.22
    initial_bias_deg: 2.0
    bias_noise_std: 0 #1e-2
  sun_sensor:
    rotate_std_deg: 0.0
    noise_std_deg: 5.0
  magnetometer:
    rotate_std_deg: 0.0
    noise_std_deg: 5.0
