%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/kevintracy/Downloads/vr3x-balloon-tracker-data.xlsx
%    Worksheet: vr3x-balloon-tracker-data
%
% Auto-generated by MATLAB on 10-Apr-2021 07:52:10

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 7);

% Specify sheet and range
opts.Sheet = "vr3x-balloon-tracker-data";
opts.DataRange = "A2:G18843";

% Specify column names and types
opts.VariableNames = ["DateTimePOSIXMS", "DateTimeUTC", "DateTimeCST", "User", "Latitude", "Longitude", "Altitudem"];
opts.SelectedVariableNames = ["DateTimePOSIXMS", "DateTimeUTC", "DateTimeCST", "User", "Latitude", "Longitude", "Altitudem"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double"];

% Import the data
vr3xballoontrackerdata = readtable("/Users/kevintracy/Downloads/vr3x-balloon-tracker-data.xlsx", opts, "UseExcel", false);

%% Convert to output type
vr3xballoontrackerdata = table2array(vr3xballoontrackerdata);
DATA = vr3xballoontrackerdata;

%% Clear temporary variables
clear opts